name: Java CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_NAME: ical4j-spring-example
  IMAGE_NAME: my-docker-registry/${APP_NAME}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Build and test app
      run: ./gradlew build

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .

    - name: Push Docker image to registry
      run: docker push $IMAGE_NAME

    - name: Deploy app to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker pull $IMAGE_NAME
          docker stop ${APP_NAME} || true
          docker rm ${APP_NAME} || true
          docker run -d --name ${APP_NAME} -p 8080:8080 $IMAGE_NAME
