name: Java CI with Gradle

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build with Gradle
      run: gradle build

    - name: Test with JUnit
      run: gradle test

    - name: Create Jacoco report
      run: gradle jacocoTestReport

    - name: Archive test reports
      uses: actions/upload-artifact@v3
      with:
        name: junit-reports
        path: app/build/reports/

    - name: Upload coverage reports to Codecov
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      uses: codecov/codecov-action@v3
